import type { Talk } from "./types";

export const talks: Talk[] = [
  {
    eventEs: "TED Talk",
    eventEn: "TED Talk",
    topicEs: "Rompiendo el molde con IA",
    topicEn: "Breaking the mold with AI",
    year: "2023",
    city: "Cochabamba",
    youtubeUrl: "https://www.youtube.com/watch?v=9Q-G55HgvHE",
  },
  {
    eventEs: "PyCon US",
    eventEn: "PyCon US",
    topicEs: "IA, automatización y comunidad",
    topicEn: "AI, automation and community",
    year: "2025",
    city: "Pittsburgh",
    youtubeUrl: undefined,
  },
  {
    eventEs: "Nerdearla",
    eventEn: "Nerdearla",
    topicEs: "Cómo la IA cambió mi vida",
    topicEn: "How AI changed my life",
    year: "2024",
    city: "Latam",
    youtubeUrl: "https://www.youtube.com/watch?v=5L-8NO-_GZw",
  },
  {
    eventEs: "Platzi Conf Colombia",
    eventEn: "Platzi Conf Colombia",
    topicEs: "Speaker oficial",
    topicEn: "Official speaker",
    year: "2024",
    city: "Bogotá",
    youtubeUrl: undefined,
  },
  {
    eventEs: "Fuckup Nights",
    eventEn: "Fuckup Nights",
    topicEs: "Mi error favorito",
    topicEn: "My favorite mistake",
    year: "2024",
    city: "Cochabamba",
    youtubeUrl: "https://www.youtube.com/watch?v=hq3SlZgG1To",
  },
  {
    eventEs: "AWSome Women Summit",
    eventEn: "AWSome Women Summit",
    topicEs: "Organizadora",
    topicEn: "Organizer",
    year: "2025",
    city: "México",
    youtubeUrl: undefined,
  },
];
