import { Helmet } from "react-helmet-async";
import { ArrowUpRight, Check, Mail, Phone, Send, Users } from "lucide-react";
import Reveal from "../components/Reveal";
import { brands, packages, services, socialChannels, tiktokAudience } from "../data/mediaKit";

export default function Collaborations() {
  return <main className="media-kit">
    <Helmet><title>Collaborations — Carli Code</title><meta name="description" content="Collaborate with Carli Code: creator, educator and AI community builder." /></Helmet>

    <section className="media-hero"><Reveal><p className="eyebrow"><span /> CARLI CODE / MEDIA KIT 2026</p><h1>Let’s make ideas<br /><em>matter.</em></h1><p>Creator, educator and community builder translating AI and technology into content people want to share.</p><div className="media-hero-actions"><a className="button button-primary" href="#contact-form">Start a collaboration <ArrowUpRight size={18} /></a><a className="text-link" href="#rates">View rates ↓</a></div></Reveal><div className="media-hero-mark float-mark"><span>CARLI<br />CODE</span><i /><span>CONTENT<br />WITH PURPOSE</span></div></section>

    <section className="media-section media-about"><Reveal><p className="eyebrow"><span /> ABOUT THE CREATOR</p><h2>A trusted voice for<br /><em>curious people.</em></h2></Reveal><Reveal delay={120}><div><p>Hi, I’m Carli, an artificial intelligence programmer from Cochabamba, Bolivia. I began creating content from my passion for teaching and my desire to build a welcoming path into programming.</p><p>I create in Spanish for a community that is curious, practical and ready to build. I also collaborate with Google as a Women Techmakers ambassador and actively participate in the developer community.</p></div></Reveal></section>

    <section className="media-section social-section"><Reveal className="section-label"><p className="eyebrow"><span /> WHERE THE COMMUNITY LIVES</p><h2>Reach across<br /><em>four platforms.</em></h2></Reveal><div className="social-grid">{socialChannels.map((channel, index) => <Reveal delay={index * 80} key={channel.name}><a className={`social-card ${channel.accent}`} href={channel.href} target="_blank" rel="noreferrer"><span>{channel.name}</span><strong>{channel.followers}</strong><small>{channel.detail}</small><p>{channel.handle} <ArrowUpRight size={16} /></p></a></Reveal>)}</div></section>

    <section className="media-section audience-section"><Reveal className="audience-heading"><p className="eyebrow"><span /> TIKTOK AUDIENCE SNAPSHOT</p><h2>Built-in <em>discovery.</em></h2><p>Recent TikTok audience data. Audience metrics naturally change over time.</p></Reveal><Reveal delay={100}><div className="audience-top"><div><small>VIEWERS / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.viewers}</strong></div><div><small>NEW VIEWERS / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.newViewers}</strong></div><div><small>AUDIENCE</small><strong>{tiktokAudience.gender.join(" / ")}</strong></div></div></Reveal><div className="audience-grid"><Reveal delay={80}><MetricBars title="Top age ranges" data={tiktokAudience.ages} suffix="%" /></Reveal><Reveal delay={160}><MetricBars title="Top locations" data={tiktokAudience.locations} suffix="%" /></Reveal></div></section>

    <section className="media-section brands-section"><Reveal><p className="eyebrow"><span /> SELECTED COLLABORATIONS</p><h2>Brands I’ve helped<br /><em>move the conversation.</em></h2><div>{brands.map((brand, index) => <span className="brand-chip" style={{ "--brand-delay": `${index * 85}ms` }} key={brand}>{brand}</span>)}</div></Reveal></section>

    <section id="rates" className="media-section rates-section"><Reveal className="rates-heading"><div><p className="eyebrow"><span /> CONTENT PRICING</p><h2>Choose a format.<br /><em>Build momentum.</em></h2></div><p>All rates are listed in USD. Each collaboration starts with a conversation to make sure the idea fits your goals and my audience.</p></Reveal><div className="service-list">{services.map((service, index) => <Reveal delay={index * 60} key={service.name}><article className={service.featured ? "featured" : ""}><div><h3>{service.name}{service.featured && <span> Best seller</span>}</h3><p>{service.description}</p></div><strong>{service.price}</strong></article></Reveal>)}</div></section>

    <section className="media-section package-section"><Reveal><p className="eyebrow"><span /> CAMPAIGN PACKAGES</p></Reveal><div className="package-grid">{packages.map((item, index) => <Reveal delay={index * 70} key={item.name}><article className={item.featured ? "featured" : ""}><div><h3>{item.name}{item.featured && <span> ★</span>}</h3><p>{item.description}</p></div><strong>{item.price}</strong><Check size={18} /></article></Reveal>)}</div></section>

    <section id="contact-form" className="media-contact"><Reveal><p className="eyebrow"><span /> LET’S WORK TOGETHER</p><h2>Ready when you<br /><em>are.</em></h2><p className="contact-intro">Tell me about your brand, event or project. I’ll get back to you within 48 hours.</p><div className="direct-contact"><a href="mailto:carli.f.roman@gmail.com"><Mail size={18} /> carli.f.roman@gmail.com</a><a href="tel:+59169533423"><Phone size={18} /> +591 695 33423</a></div></Reveal><Reveal delay={120}><form className="collaboration-form" action="https://formspree.io/f/mrbqpbqb" method="POST"><input type="hidden" name="_subject" value="New Carli Code collaboration inquiry" /><label><span>Your name</span><input required name="name" type="text" autoComplete="name" /></label><label><span>Your email</span><input required name="email" type="email" autoComplete="email" /></label><label><span>Company / brand</span><input name="company" type="text" autoComplete="organization" /></label><label><span>Type of collaboration</span><select name="collaboration_type" defaultValue=""><option value="" disabled>Select an option</option><option>Brand campaign</option><option>Sponsored content</option><option>Speaking engagement</option><option>Community project</option><option>Other</option></select></label><label className="form-message"><span>Tell me more</span><textarea required name="message" rows="5" /></label><button className="form-submit" type="submit">Send message <Send size={17} /></button></form></Reveal></section>
  </main>;
}

function MetricBars({ title, data, suffix }) { return <div className="metric-bars"><h3>{title}</h3>{data.map((item) => <div className="metric-row" key={item.label}><div><span>{item.label}</span><b>{item.value}{suffix}</b></div><i><em style={{ width: `${item.value}%` }} /></i></div>)}</div>; }
