import { Helmet } from "react-helmet-async";
import { ArrowUpRight, Check, Mail, Phone, Users } from "lucide-react";
import { brands, packages, services, socialChannels, tiktokAudience } from "../data/mediaKit";

export default function Collaborations() {
  return <main className="media-kit">
    <Helmet><title>Collaborations — Carli Code</title><meta name="description" content="Collaborate with Carli Code: creator, educator and AI community builder." /></Helmet>
    <section className="media-hero"><div><p className="eyebrow"><span /> CARLI CODE / MEDIA KIT 2026</p><h1>Let’s make ideas<br /><em>matter.</em></h1><p>Creator, educator and community builder translating AI and technology into content people want to share.</p><div className="media-hero-actions"><a className="button button-primary" href="mailto:carli.f.roman@gmail.com">Start a collaboration <ArrowUpRight size={18} /></a><a className="text-link" href="#rates">View rates ↓</a></div></div><div className="media-hero-mark"><span>CARLI<br />CODE</span><i /><span>CONTENT<br />WITH PURPOSE</span></div></section>
    <section className="media-section media-about"><div><p className="eyebrow"><span /> ABOUT THE CREATOR</p><h2>A trusted voice for<br /><em>curious people.</em></h2></div><div><p>Hi, I’m Carli, an artificial intelligence programmer from Cochabamba, Bolivia. I began creating content from my passion for teaching and my desire to build a welcoming path into programming.</p><p>I create in Spanish for a community that is curious, practical and ready to build. I also collaborate with Google as a Women Techmakers ambassador and actively participate in the developer community.</p></div></section>
    <section className="media-section social-section"><div className="section-label"><p className="eyebrow"><span /> WHERE THE COMMUNITY LIVES</p><h2>Reach across<br /><em>four platforms.</em></h2></div><div className="social-grid">{socialChannels.map((channel) => <a className={`social-card ${channel.accent}`} href={channel.href} target="_blank" rel="noreferrer" key={channel.name}><span>{channel.name}</span><strong>{channel.followers}</strong><small>{channel.detail}</small><p>{channel.handle} <ArrowUpRight size={16} /></p></a>)}</div></section>
    <section className="media-section audience-section"><div className="audience-heading"><p className="eyebrow"><span /> TIKTOK AUDIENCE SNAPSHOT</p><h2>Built-in <em>discovery.</em></h2><p>Recent TikTok audience data. Audience metrics naturally change over time.</p></div><div className="audience-top"><div><small>VIEWERS / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.viewers}</strong></div><div><small>NEW VIEWERS / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.newViewers}</strong></div><div><small>AUDIENCE</small><strong>{tiktokAudience.gender.join(" / ")}</strong></div></div><div className="audience-grid"><MetricBars title="Top age ranges" data={tiktokAudience.ages} suffix="%" /><MetricBars title="Top locations" data={tiktokAudience.locations} suffix="%" /></div></section>
    <section className="media-section brands-section"><p className="eyebrow"><span /> SELECTED COLLABORATIONS</p><h2>Brands I’ve helped<br /><em>move the conversation.</em></h2><div>{brands.map((brand) => <span key={brand}>{brand}</span>)}</div></section>
    <section id="rates" className="media-section rates-section"><div className="rates-heading"><p className="eyebrow"><span /> CONTENT PRICING</p><h2>Choose a format.<br /><em>Build momentum.</em></h2><p>All rates are listed in USD. Each collaboration starts with a conversation to make sure the idea fits your goals and my audience.</p></div><div className="service-list">{services.map((service) => <article className={service.featured ? "featured" : ""} key={service.name}><div><h3>{service.name}{service.featured && <span> Best seller</span>}</h3><p>{service.description}</p></div><strong>{service.price}</strong></article>)}</div></section>
    <section className="media-section package-section"><p className="eyebrow"><span /> CAMPAIGN PACKAGES</p><div className="package-grid">{packages.map((item) => <article className={item.featured ? "featured" : ""} key={item.name}><div><h3>{item.name}{item.featured && <span> ★</span>}</h3><p>{item.description}</p></div><strong>{item.price}</strong><Check size={18} /></article>)}</div></section>
    <section className="media-contact"><div><p className="eyebrow"><span /> LET’S WORK TOGETHER</p><h2>Ready when you<br /><em>are.</em></h2></div><div><a href="mailto:carli.f.roman@gmail.com"><Mail size={20} /> carli.f.roman@gmail.com</a><a href="tel:+59169533423"><Phone size={20} /> +591 695 33423</a><p><Users size={18} /> For brands, campaigns, speaking opportunities and community projects.</p></div></section>
  </main>;
}

function MetricBars({ title, data, suffix }) { return <div className="metric-bars"><h3>{title}</h3>{data.map((item) => <div className="metric-row" key={item.label}><div><span>{item.label}</span><b>{item.value}{suffix}</b></div><i><em style={{ width: `${item.value}%` }} /></i></div>)}</div>; }
