import { Helmet } from "react-helmet-async";
import { ArrowUpRight, Check, Mail, Phone, Send, Users } from "lucide-react";
import Reveal from "../components/Reveal";
import { useLanguage } from "../components/LanguageProvider";
import { brands, packages, services, socialChannels, tiktokAudience } from "../data/mediaKit";

export default function Collaborations() {
  const { language } = useLanguage();
  const copy = language === "es" ? {
    kit: "CARLI CODE / MEDIA KIT 2026", hero: <>Hagamos que las ideas<br /><em>importen.</em></>, heroText: "Creadora, educadora y community builder que convierte la IA y la tecnología en contenido que las personas quieren compartir.", start: "Empecemos una colaboración", rates: "Ver tarifas ↓", about: "SOBRE LA CREADORA", aboutTitle: <>Una voz cercana para<br /><em>personas curiosas.</em></>, aboutOne: "Hola, soy Carli, programadora de inteligencia artificial de Cochabamba, Bolivia. Comencé a crear contenido desde mi pasión por enseñar y por construir un camino acogedor hacia la programación.", aboutTwo: "Creo en español para una comunidad curiosa, práctica y lista para construir. También colaboro con Google como embajadora de Women Techmakers y participo activamente en la comunidad de desarrolladores.", socialLabel: "DÓNDE VIVE LA COMUNIDAD", socialTitle: <>Alcance en<br /><em>cuatro plataformas.</em></>, audience: "AUDIENCIA DE TIKTOK", audienceTitle: <>Descubrimiento <em>incorporado.</em></>, audienceText: "Datos recientes de audiencia en TikTok. Las métricas cambian naturalmente con el tiempo.", viewers: "ESPECTADORES", newViewers: "NUEVOS ESPECTADORES", selected: "COLABORACIONES SELECCIONADAS", brands: <>Marcas con las que<br /><em>movimos la conversación.</em></>, pricing: "TARIFAS DE CONTENIDO", pricingTitle: <>Elige un formato.<br /><em>Genera impulso.</em></>, pricingText: "Las tarifas están expresadas en USD. Cada colaboración comienza con una conversación para asegurar que la idea se conecte con tus objetivos y mi audiencia.", packages: "PAQUETES DE CAMPAÑA", together: "TRABAJEMOS JUNTAS", contactTitle: <>Lista cuando tú<br /><em>lo estés.</em></>, contactText: "Cuéntame sobre tu marca, evento o proyecto. Responderé en menos de 48 horas.", name: "Tu nombre", email: "Tu email", company: "Empresa / marca", type: "Tipo de colaboración", message: "Cuéntame más", choose: "Elige una opción", send: "Enviar mensaje", viewersLabel: "ESPECTADORES", newLabel: "NUEVOS ESPECTADORES", audienceLabel: "AUDIENCIA", ages: "Edades principales", locations: "Ubicaciones principales"
  } : {
    kit: "CARLI CODE / MEDIA KIT 2026", hero: <>Let’s make ideas<br /><em>matter.</em></>, heroText: "Creator, educator and community builder translating AI and technology into content people want to share.", start: "Start a collaboration", rates: "View rates ↓", about: "ABOUT THE CREATOR", aboutTitle: <>A trusted voice for<br /><em>curious people.</em></>, aboutOne: "Hi, I’m Carli, an artificial intelligence programmer from Cochabamba, Bolivia. I began creating content from my passion for teaching and my desire to build a welcoming path into programming.", aboutTwo: "I create in Spanish for a community that is curious, practical and ready to build. I also collaborate with Google as a Women Techmakers ambassador and actively participate in the developer community.", socialLabel: "WHERE THE COMMUNITY LIVES", socialTitle: <>Reach across<br /><em>four platforms.</em></>, audience: "TIKTOK AUDIENCE SNAPSHOT", audienceTitle: <>Built-in <em>discovery.</em></>, audienceText: "Recent TikTok audience data. Audience metrics naturally change over time.", viewers: "VIEWERS", newViewers: "NEW VIEWERS", selected: "SELECTED COLLABORATIONS", brands: <>Brands I’ve helped<br /><em>move the conversation.</em></>, pricing: "CONTENT PRICING", pricingTitle: <>Choose a format.<br /><em>Build momentum.</em></>, pricingText: "All rates are listed in USD. Each collaboration starts with a conversation to make sure the idea fits your goals and my audience.", packages: "CAMPAIGN PACKAGES", together: "LET’S WORK TOGETHER", contactTitle: <>Ready when you<br /><em>are.</em></>, contactText: "Tell me about your brand, event or project. I’ll get back to you within 48 hours.", name: "Your name", email: "Your email", company: "Company / brand", type: "Type of collaboration", message: "Tell me more", choose: "Select an option", send: "Send message", viewersLabel: "VIEWERS", newLabel: "NEW VIEWERS", audienceLabel: "AUDIENCE", ages: "Top age ranges", locations: "Top locations"
  };
  return <main className="media-kit">
    <Helmet><title>Collaborations — Carli Code</title><meta name="description" content="Collaborate with Carli Code: creator, educator and AI community builder." /></Helmet>

    <section className="media-hero"><Reveal><p className="eyebrow"><span /> {copy.kit}</p><h1>{copy.hero}</h1><p>{copy.heroText}</p><div className="media-hero-actions"><a className="button button-primary" href="#contact-form">{copy.start} <ArrowUpRight size={18} /></a><a className="text-link" href="#rates">{copy.rates}</a></div></Reveal><div className="media-hero-mark float-mark"><span>CARLI<br />CODE</span><i /><span>CONTENT<br />WITH PURPOSE</span></div></section>

    <section className="media-section media-about"><Reveal><p className="eyebrow"><span /> {copy.about}</p><h2>{copy.aboutTitle}</h2></Reveal><Reveal delay={120}><div><p>{copy.aboutOne}</p><p>{copy.aboutTwo}</p></div></Reveal></section>

    <section className="media-section social-section"><Reveal className="section-label"><p className="eyebrow"><span /> {copy.socialLabel}</p><h2>{copy.socialTitle}</h2></Reveal><div className="social-grid">{socialChannels.map((channel, index) => <Reveal delay={index * 80} key={channel.name}><a className={`social-card ${channel.accent}`} href={channel.href} target="_blank" rel="noreferrer"><span>{channel.name}</span><strong>{channel.followers}</strong><small>{channel.detail}</small><p>{channel.handle} <ArrowUpRight size={16} /></p></a></Reveal>)}</div></section>

    <section className="media-section audience-section"><Reveal className="audience-heading"><p className="eyebrow"><span /> {copy.audience}</p><h2>{copy.audienceTitle}</h2><p>{copy.audienceText}</p></Reveal><Reveal delay={100}><div className="audience-top"><div><small>{copy.viewersLabel} / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.viewers}</strong></div><div><small>{copy.newLabel} / {tiktokAudience.period.toUpperCase()}</small><strong>{tiktokAudience.newViewers}</strong></div><div><small>{copy.audienceLabel}</small><strong>{tiktokAudience.gender.join(" / ")}</strong></div></div></Reveal><div className="audience-grid"><Reveal delay={80}><MetricBars title={copy.ages} data={tiktokAudience.ages} suffix="%" /></Reveal><Reveal delay={160}><MetricBars title={copy.locations} data={tiktokAudience.locations} suffix="%" /></Reveal></div></section>

    <section className="media-section brands-section"><Reveal><p className="eyebrow"><span /> {copy.selected}</p><h2>{copy.brands}</h2><div>{brands.map((brand, index) => <span className="brand-chip" style={{ "--brand-delay": `${index * 85}ms` }} key={brand}>{brand}</span>)}</div></Reveal></section>

    <section id="rates" className="media-section rates-section"><Reveal className="rates-heading"><div><p className="eyebrow"><span /> {copy.pricing}</p><h2>{copy.pricingTitle}</h2></div><p>{copy.pricingText}</p></Reveal><div className="service-list">{services.map((service, index) => <Reveal delay={index * 60} key={service.name}><article className={service.featured ? "featured" : ""}><div><h3>{service.name}{service.featured && <span> Best seller</span>}</h3><p>{service.description}</p></div><strong>{service.price}</strong></article></Reveal>)}</div></section>

    <section className="media-section package-section"><Reveal><p className="eyebrow"><span /> {copy.packages}</p></Reveal><div className="package-grid">{packages.map((item, index) => <Reveal delay={index * 70} key={item.name}><article className={item.featured ? "featured" : ""}><div><h3>{item.name}{item.featured && <span> ★</span>}</h3><p>{item.description}</p></div><strong>{item.price}</strong><Check size={18} /></article></Reveal>)}</div></section>

    <section id="contact-form" className="media-contact"><Reveal><p className="eyebrow"><span /> {copy.together}</p><h2>{copy.contactTitle}</h2><p className="contact-intro">{copy.contactText}</p><div className="direct-contact"><a href="mailto:carli.f.roman@gmail.com"><Mail size={18} /> carli.f.roman@gmail.com</a><a href="tel:+59169533423"><Phone size={18} /> +591 695 33423</a></div></Reveal><Reveal delay={120}><form className="collaboration-form" action="https://formspree.io/f/mrbqpbqb" method="POST"><input type="hidden" name="_subject" value="New Carli Code collaboration inquiry" /><label><span>{copy.name}</span><input required name="name" type="text" autoComplete="name" /></label><label><span>{copy.email}</span><input required name="email" type="email" autoComplete="email" /></label><label><span>{copy.company}</span><input name="company" type="text" autoComplete="organization" /></label><label><span>{copy.type}</span><select name="collaboration_type" defaultValue=""><option value="" disabled>{copy.choose}</option><option>Brand campaign</option><option>Sponsored content</option><option>Speaking engagement</option><option>Community project</option><option>Other</option></select></label><label className="form-message"><span>{copy.message}</span><textarea required name="message" rows="5" /></label><button className="form-submit" type="submit">{copy.send} <Send size={17} /></button></form></Reveal></section>
  </main>;
}

function MetricBars({ title, data, suffix }) { return <div className="metric-bars"><h3>{title}</h3>{data.map((item) => <div className="metric-row" key={item.label}><div><span>{item.label}</span><b>{item.value}{suffix}</b></div><i><em style={{ width: `${item.value}%` }} /></i></div>)}</div>; }
